version: "3.9"
services:
  controller:
    build: ./controller
    image: gianlucaaguzzi/fastchat-controller:latest
  worker:
    build: ./worker
    image: gianlucaaguzzi/fastchat-worker:latest
    environment:
      - CONTROLLER_HOST
      - WORKER_HOST
  endpoint:
    build: ./endpoint
    image: gianlucaaguzzi/fastchat-endpoint:latest
    ports: 
        - "${ENDPOINT_PORT}:${ENDPOINT_PORT}"
    environment:
      - CONTROLLER_HOST
      - ENDPOINT_PORT
    depends_on:
      - controller
      - worker
