version: "3.9"
services:
  controller:
    image: gianlucaaguzzi/fastchat-controller:latest
    environment:
      - HOST
    network_mode: "service:endpoint"
  worker:
    image: gianlucaaguzzi/fastchat-worker:latest
    environment:
      - HOST
    network_mode: "service:endpoint"
  endpoint:
    image: gianlucaaguzzi/fastchat-endpoint:latest
    ports: 
      - "8000:21003"
    environment:
      - HOST
